import streamlit as st  
st.checkbox('Yes')
st.checkbox('No') 
st.toggle('Turn on', 'Turn off')  
st.button('Click Me! :)')  
st.radio('Pick your gender', ['Male', 'Female'])  
st.selectbox('Pick a fruit', ['Apple', 'Banana', 'Orange', 'Pineapple', 'Watermelon'])  
st.multiselect('Choose a planet', ['Jupiter', 'Mars', 'Neptune', 'Earth', 'Venus'])  
st.select_slider('Pick a mark', ['Bad', 'Good', 'Excellent'])  
st.slider('Pick a number', 0, 100)  

st.number_input('Pick a number', 0, 20)  
st.text_input('Email address')  
st.date_input('Traveling date')  
st.time_input('School time')  
st.text_area('Description')  
st.file_uploader('Upload a photo')  
st.color_picker('Choose your favorite color')